// Generated by scripts/build-jscore.mjs from wiz-light-core — do not edit by hand.
var WizCore = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // packages/core/src/pure.js
  var pure_exports = {};
  __export(pure_exports, {
    DEFAULT_PRESETS: () => DEFAULT_PRESETS,
    DEFAULT_STATE: () => DEFAULT_STATE,
    DIMMING_MAX: () => DIMMING_MAX,
    DIMMING_MIN: () => DIMMING_MIN,
    SCENES: () => SCENES,
    SCENE_HINTS: () => SCENE_HINTS,
    SPEED_MAX: () => SPEED_MAX,
    SPEED_MIN: () => SPEED_MIN,
    TEMP_MAX: () => TEMP_MAX,
    TEMP_MIN: () => TEMP_MIN,
    applyPreset: () => applyPreset,
    buildSetPilotParams: () => buildSetPilotParams,
    clampBrightness: () => clampBrightness,
    clampInt: () => clampInt,
    clampRgb: () => clampRgb,
    clampSpeed: () => clampSpeed,
    clampTemp: () => clampTemp,
    describeDevice: () => describeDevice,
    deviceBoundsFromConfig: () => deviceBoundsFromConfig,
    deviceCapabilities: () => deviceCapabilities,
    dimToWarmCurveFromConfig: () => dimToWarmCurveFromConfig,
    findScene: () => findScene,
    formatMac: () => formatMac,
    hexToRgb: () => hexToRgb,
    hsToWheel: () => hsToWheel,
    hsvToRgb: () => hsvToRgb,
    isValidHex: () => isValidHex,
    isValidIp: () => isValidIp,
    kelvinToRgb: () => kelvinToRgb,
    normalizeHex: () => normalizeHex,
    parsePilot: () => parsePilot,
    perceivedRgb: () => perceivedRgb,
    rgbToHex: () => rgbToHex,
    rgbToHsv: () => rgbToHsv,
    rgbToWhiteMixed: () => rgbToWhiteMixed,
    sceneHint: () => sceneHint,
    sceneName: () => sceneName,
    scenesForDevice: () => scenesForDevice,
    stateMatchesPreset: () => stateMatchesPreset,
    toDimming: () => toDimming,
    warmGlowKelvin: () => warmGlowKelvin,
    wheelToHS: () => wheelToHS,
    whiteMixedToRgb: () => whiteMixedToRgb
  });

  // packages/core/src/color.js
  var TEMP_MIN = 2200;
  var TEMP_MAX = 6500;
  var clampByte = (n) => {
    const r = Math.round(n);
    return Number.isFinite(r) ? Math.max(0, Math.min(255, r)) : 0;
  };
  function rgbToHsv([r, g, b]) {
    const rf = r / 255;
    const gf = g / 255;
    const bf = b / 255;
    const max = Math.max(rf, gf, bf);
    const min = Math.min(rf, gf, bf);
    const v = max;
    if (max === min) return [0, 0, v];
    const d = max - min;
    const s = d / max;
    const rc = (max - rf) / d;
    const gc = (max - gf) / d;
    const bc = (max - bf) / d;
    let h;
    if (rf === max) h = bc - gc;
    else if (gf === max) h = 2 + rc - bc;
    else h = 4 + gc - rc;
    h = h / 6 % 1;
    if (h < 0) h += 1;
    return [h, s, v];
  }
  function hsvToRgb([h, s, v]) {
    if (s === 0) {
      const c = clampByte(v * 255);
      return [c, c, c];
    }
    const i = Math.floor(h * 6) % 6;
    const f = h * 6 - Math.floor(h * 6);
    const p = v * (1 - s);
    const q = v * (1 - s * f);
    const t = v * (1 - s * (1 - f));
    const table = [
      [v, t, p],
      [q, v, p],
      [p, v, t],
      [p, q, v],
      [t, p, v],
      [v, p, q]
    ];
    const [rf, gf, bf] = table[(i + 6) % 6];
    return [clampByte(rf * 255), clampByte(gf * 255), clampByte(bf * 255)];
  }
  function rgbToHex([r, g, b]) {
    const hex = (n) => clampByte(n).toString(16).padStart(2, "0");
    return `#${hex(r)}${hex(g)}${hex(b)}`;
  }
  function hexToRgb(hex) {
    if (typeof hex !== "string") return null;
    const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
    if (!m) return null;
    const v = parseInt(m[1], 16);
    return [v >> 16 & 255, v >> 8 & 255, v & 255];
  }
  function kelvinToRgb(kelvin) {
    const t = kelvin / 100;
    let r;
    let g;
    let b;
    if (t <= 66) {
      r = 255;
      g = 99.4708025861 * Math.log(t) - 161.1195681661;
      b = t <= 19 ? 0 : 138.5177312231 * Math.log(t - 10) - 305.0447927307;
    } else {
      r = 329.698727446 * (t - 60) ** -0.1332047592;
      g = 288.1221695283 * (t - 60) ** -0.0755148492;
      b = 255;
    }
    return [clampByte(r), clampByte(g), clampByte(b)];
  }
  var WHITE_WASH_FULL = 280;
  function perceivedRgb([r, g, b], c = 0, w = 0) {
    if (!c && !w) return [clampByte(r), clampByte(g), clampByte(b)];
    const max = Math.max(r, g, b, 1);
    const t = Math.min(1, (Math.max(0, c) + Math.max(0, w)) / WHITE_WASH_FULL);
    const wash = (chan) => (chan / max * (1 - t) + t) * 255;
    return [clampByte(wash(r)), clampByte(wash(g)), clampByte(wash(b))];
  }
  function wheelToHS(x, y, size) {
    const c = size / 2;
    const dx = x - c;
    const dy = y - c;
    const dist = Math.hypot(dx, dy);
    if (dist > c) return null;
    const hue = (Math.atan2(dy, dx) + Math.PI) / (2 * Math.PI);
    const sat = Math.min(1, dist / c);
    return { h: hue, s: sat };
  }
  function hsToWheel(h, s, size) {
    const c = size / 2;
    const r = s * c;
    const angle = h * 2 * Math.PI - Math.PI;
    return { x: c + Math.cos(angle) * r, y: c + Math.sin(angle) * r };
  }

  // packages/core/src/validate.js
  var DIMMING_MIN = 10;
  var DIMMING_MAX = 100;
  var octet = "(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)";
  var IPV4 = new RegExp(`^${octet}(\\.${octet}){3}$`);
  function isValidIp(value) {
    return typeof value === "string" && IPV4.test(value.trim());
  }
  function isValidHex(value) {
    return typeof value === "string" && /^#?[0-9a-f]{6}$/i.test(value.trim());
  }
  function normalizeHex(value, fallback) {
    if (!isValidHex(value)) return fallback;
    const v = value.trim();
    return `#${(v.startsWith("#") ? v.slice(1) : v).toLowerCase()}`;
  }
  function formatMac(mac) {
    if (typeof mac !== "string" || !/^[0-9a-f]{12}$/i.test(mac)) return mac;
    return mac.match(/.{2}/g).join(":").toUpperCase();
  }
  function clampInt(n, lo, hi) {
    const v = Math.round(Number(n));
    if (Number.isNaN(v)) return lo;
    return Math.max(lo, Math.min(hi, v));
  }
  var clampBrightness = (n) => clampInt(n, 0, 100);
  var clampTemp = (k) => clampInt(k, TEMP_MIN, TEMP_MAX);
  var SPEED_MIN = 10;
  var SPEED_MAX = 200;
  var clampSpeed = (n) => clampInt(n, SPEED_MIN, SPEED_MAX);
  var toDimming = (brightness) => clampInt(brightness, DIMMING_MIN, DIMMING_MAX);
  var clampRgb = (rgb) => rgb.map((c) => clampInt(c, 0, 255));

  // packages/core/src/model.js
  var DEFAULT_STATE = Object.freeze({
    on: false,
    mode: "rgb",
    rgb: [255, 255, 255],
    temp: 4e3,
    brightness: 100
  });
  function parsePilot(result) {
    if (!result || typeof result !== "object") return null;
    const on = result.state === void 0 ? true : Boolean(result.state);
    const brightness = result.dimming === void 0 ? DEFAULT_STATE.brightness : clampBrightness(result.dimming);
    const sceneId = Number(result.sceneId);
    if (Number.isInteger(sceneId) && sceneId > 0) {
      const scene = { id: sceneId };
      if (result.speed != null) scene.speed = clampSpeed(result.speed);
      return { on, mode: "rgb", rgb: DEFAULT_STATE.rgb, temp: DEFAULT_STATE.temp, brightness, scene };
    }
    const { r, g, b, temp } = result;
    const hasRgb = r != null && g != null && b != null && (r || g || b);
    if (hasRgb) {
      return { on, mode: "rgb", rgb: clampRgb([r, g, b]), temp: DEFAULT_STATE.temp, brightness };
    }
    if (temp != null) {
      return { on, mode: "white", rgb: DEFAULT_STATE.rgb, temp: clampTemp(temp), brightness };
    }
    return { on, mode: "rgb", rgb: DEFAULT_STATE.rgb, temp: DEFAULT_STATE.temp, brightness };
  }
  function buildSetPilotParams(state, bounds = {}, { whiteMix = false } = {}) {
    if (!state.on) return { state: false };
    const dimMin = bounds.dimMin ?? DIMMING_MIN;
    const tempMin = bounds.tempMin ?? TEMP_MIN;
    const tempMax = bounds.tempMax ?? TEMP_MAX;
    const params = { state: true, dimming: clampInt(state.brightness, dimMin, DIMMING_MAX) };
    if (state.scene) {
      params.sceneId = Number(state.scene.id);
      if (state.scene.speed != null) params.speed = clampSpeed(state.scene.speed);
      return params;
    }
    if (state.mode === "white") {
      params.temp = clampInt(state.temp, tempMin, tempMax);
    } else if (whiteMix) {
      Object.assign(params, rgbToWhiteMixed(clampRgb(state.rgb)));
    } else {
      const [r, g, b] = clampRgb(state.rgb);
      Object.assign(params, { r, g, b });
    }
    return params;
  }
  function rgbToWhiteMixed([r, g, b]) {
    const white = Math.min(r, g, b);
    return { r: r - white, g: g - white, b: b - white, c: white, w: white };
  }
  function whiteMixedToRgb(rgb, c = 0, w = 0) {
    if (c !== w) return null;
    const white = clampInt(c, 0, 255);
    return clampRgb(rgb.map((channel) => Number(channel) + white));
  }
  function deviceBoundsFromConfig(modelConfig) {
    const bounds = {};
    if (!modelConfig || typeof modelConfig !== "object") return bounds;
    const cct = modelConfig.cctRange;
    if (Array.isArray(cct)) {
      const values = cct.map(Number).filter((n) => Number.isFinite(n) && n > 0);
      if (values.length) {
        bounds.tempMin = Math.min(...values);
        bounds.tempMax = Math.max(...values);
      }
    }
    const dimMin = Number(modelConfig.minDimLevel);
    if (Number.isFinite(dimMin) && dimMin > 0) bounds.dimMin = dimMin;
    return bounds;
  }
  function deviceCapabilities(modelConfig) {
    if (!modelConfig || typeof modelConfig !== "object") {
      return { rgb: false, tunableWhite: false, white: false };
    }
    const { tempMin, tempMax } = deviceBoundsFromConfig(modelConfig);
    const pwm = Array.isArray(modelConfig.pwmRanges) ? modelConfig.pwmRanges : [];
    let channels = 0;
    for (let i = 0; i + 1 < pwm.length; i += 2) {
      if (Number(pwm[i + 1]) > Number(pwm[i])) channels += 1;
    }
    const whiteChannels = Number(modelConfig.nowc);
    const hasRange = Number.isFinite(tempMin) && Number.isFinite(tempMax) && tempMin < tempMax;
    const tunableWhite = hasRange || whiteChannels >= 2;
    const white = tunableWhite || Number.isFinite(tempMin) || whiteChannels >= 1;
    const caps = { rgb: channels >= 3, tunableWhite, white };
    if (Number.isFinite(tempMin)) caps.tempMin = tempMin;
    if (Number.isFinite(tempMax)) caps.tempMax = tempMax;
    return caps;
  }
  function describeDevice(modelConfig) {
    const { rgb, tunableWhite, white, tempMin, tempMax } = deviceCapabilities(modelConfig);
    const hasRange = Number.isFinite(tempMin) && Number.isFinite(tempMax) && tempMin < tempMax;
    const parts = [];
    if (rgb) parts.push("RGB");
    if (tunableWhite) {
      parts.push(hasRange ? `tunable white ${tempMin}\u2013${tempMax} K` : "tunable white");
    } else if (white) {
      parts.push("white");
    }
    return parts.join(" + ");
  }
  function dimToWarmCurveFromConfig(userConfig) {
    const raw = userConfig && typeof userConfig === "object" ? userConfig.dim2WarmPoints : null;
    if (!Array.isArray(raw)) return [];
    return raw.map(
      (pair) => Array.isArray(pair) && pair.length >= 2 ? { kelvin: Number(pair[0]), brightness: Number(pair[1]) } : null
    ).filter((p) => p && Number.isFinite(p.kelvin) && Number.isFinite(p.brightness)).sort((a, b) => a.brightness - b.brightness);
  }
  function warmGlowKelvin(brightness, curve = [], range = {}) {
    const kelvins = curve.map((p) => Number(p?.kelvin)).filter((k) => Number.isFinite(k) && k > 0);
    const lo = Number.isFinite(range.min) ? range.min : TEMP_MIN;
    const hi = Number.isFinite(range.max) ? range.max : TEMP_MAX;
    const warm = Math.max(lo, kelvins.length ? Math.min(...kelvins) : lo);
    const cool = Math.min(hi, kelvins.length ? Math.max(...kelvins) : hi);
    if (cool <= warm) return warm;
    const t = clampInt(brightness, 0, 100) / 100;
    return Math.round(warm + (cool - warm) * t);
  }
  function applyPreset(state, preset) {
    const brightness = clampBrightness(preset.brightness ?? state.brightness);
    const base = { ...state };
    delete base.scene;
    if (preset.mode === "white") {
      return { ...base, on: true, mode: "white", temp: clampTemp(preset.temp), brightness };
    }
    return {
      ...base,
      on: true,
      mode: "rgb",
      rgb: clampRgb([preset.r, preset.g, preset.b]),
      brightness
    };
  }
  function stateMatchesPreset(state, preset) {
    if (!state.on || state.scene) return false;
    if (preset.mode !== state.mode) return false;
    if ((preset.brightness ?? 100) !== state.brightness) return false;
    if (preset.mode === "rgb") {
      return preset.r === state.rgb[0] && preset.g === state.rgb[1] && preset.b === state.rgb[2];
    }
    return preset.temp === state.temp;
  }
  var DEFAULT_PRESETS = Object.freeze({
    rgb: {
      Red: { mode: "rgb", r: 255, g: 0, b: 0, brightness: 100 },
      Green: { mode: "rgb", r: 0, g: 255, b: 0, brightness: 100 },
      Blue: { mode: "rgb", r: 0, g: 0, b: 255, brightness: 100 },
      Purple: { mode: "rgb", r: 128, g: 0, b: 255, brightness: 100 },
      Sunset: { mode: "rgb", r: 255, g: 120, b: 40, brightness: 100 },
      Aqua: { mode: "rgb", r: 0, g: 255, b: 255, brightness: 100 }
    },
    white: {
      "Full White": { mode: "white", temp: 6500, brightness: 100 },
      Warmish: { mode: "white", temp: 4e3, brightness: 100 },
      Relax: { mode: "white", temp: 3e3, brightness: 100 },
      "Full Warm": { mode: "white", temp: TEMP_MIN, brightness: 100 },
      "Dim Relax": { mode: "white", temp: 2700, brightness: 40 },
      "Dim White": { mode: "white", temp: 6500, brightness: 40 }
    }
  });

  // packages/core/src/scenes.js
  var SCENES = Object.freeze({
    1: "Ocean",
    2: "Romance",
    3: "Sunset",
    4: "Party",
    5: "Fireplace",
    6: "Cozy",
    7: "Forest",
    8: "Pastel Colors",
    9: "Wake-up",
    10: "Bedtime",
    11: "Warm White",
    12: "Daylight",
    13: "Cool White",
    14: "Night Light",
    15: "Focus",
    16: "Relax",
    17: "True Colors",
    18: "TV Time",
    19: "Plantgrowth",
    20: "Spring",
    21: "Summer",
    22: "Fall",
    23: "Deep-dive",
    24: "Jungle",
    25: "Mojito",
    26: "Club",
    27: "Christmas",
    28: "Halloween",
    29: "Candlelight",
    30: "Golden White",
    31: "Pulse",
    32: "Steampunk",
    33: "Diwali",
    34: "White",
    35: "Alarm",
    36: "Snowy Sky"
  });
  var SCENE_HINTS = Object.freeze({
    1: "Rolling blues and teals",
    2: "Soft warm pinks and reds",
    3: "Orange \u2192 pink \u2192 purple fade",
    4: "Fast multicolour cycle",
    5: "Flickering warm orange",
    6: "Dim, cosy warm white",
    7: "Gentle shifting greens",
    8: "Soft drifting pastels",
    9: "Slowly brightens, warm \u2192 cool",
    10: "Slowly dims to warm",
    11: "Steady warm white",
    12: "Neutral daylight white",
    13: "Crisp cool white",
    14: "Very dim warm glow",
    15: "Bright, cool focus white",
    16: "Soft, calm warm white",
    17: "Saturated colour cycle",
    18: "Muted ambient backlight",
    19: "Magenta/pink grow light",
    20: "Fresh greens and pastels",
    21: "Warm, vivid summer hues",
    22: "Ambers and deep oranges",
    23: "Deep ocean blues",
    24: "Greens and warm yellows",
    25: "Lime and mint greens",
    26: "Bold pulsing club colours",
    27: "Festive red and green",
    28: "Eerie orange and purple",
    29: "Warm candle flicker",
    30: "Warm golden white",
    31: "Single colour, pulsing",
    32: "Warm amber and brass",
    33: "Festive golds and bright colour",
    34: "Plain bright white",
    35: "Bright, alerting light",
    36: "Cool wintry blues and whites"
  });
  var WHITE_SCENE_IDS = /* @__PURE__ */ new Set([6, 9, 10, 11, 12, 13, 14, 29, 30, 34]);
  function sceneName(id) {
    return SCENES[id] ?? null;
  }
  function sceneHint(id) {
    return SCENE_HINTS[id] ?? "";
  }
  function findScene(nameOrId) {
    if (nameOrId == null) return null;
    const asNum = Number(nameOrId);
    if (Number.isInteger(asNum) && SCENES[asNum]) return { id: asNum, name: SCENES[asNum] };
    if (typeof nameOrId === "string") {
      const needle = nameOrId.trim().toLowerCase();
      for (const [id, name] of Object.entries(SCENES)) {
        if (name.toLowerCase() === needle) return { id: Number(id), name };
      }
    }
    return null;
  }
  function scenesForDevice(modelConfig) {
    const { rgb, white } = deviceCapabilities(modelConfig);
    const whiteOnly = white && !rgb;
    return Object.entries(SCENES).filter(([id]) => !whiteOnly || WHITE_SCENE_IDS.has(Number(id))).map(([id, name]) => ({ id: Number(id), name, hint: SCENE_HINTS[id] ?? "" }));
  }
  return __toCommonJS(pure_exports);
})();
