// Bundles the pure wiz-light-core API (color + validate + model) into a single
// classic script exposing a global `WizCore`, for the macOS app to evaluate in
// a JavaScriptCore context. JSCore has no ES-module loader, hence the IIFE.
//
// Output is a generated artifact consumed by the Swift package as a resource.
// Regenerate with: pnpm build:jscore

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'apps/macos/Sources/WizKit/Resources/wiz-core.global.js');

await build({
  entryPoints: [path.join(root, 'packages/core/src/pure.js')],
  bundle: true,
  format: 'iife',
  globalName: 'WizCore',
  target: ['es2021'],
  legalComments: 'none',
  banner: {
    js: '// Generated by scripts/build-jscore.mjs from wiz-light-core — do not edit by hand.',
  },
  outfile,
});

console.log(`built ${path.relative(root, outfile)}`);
